# Generated by Django 5.0.6 on 2024-06-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Independientes', '0008_independiente_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='independiente',
            name='salarioBase',
        ),
    ]
