# Generated by Django 5.0.6 on 2024-06-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0009_calculos_novedades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculos',
            name='nivel_riesgo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
