# Generated by Django 5.0.6 on 2024-06-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0010_alter_calculos_nivel_riesgo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculos',
            name='nivel_riesgo',
            field=models.CharField(blank=True, choices=[('Nivel 1', 'Mínimo'), ('Nivel 2', 'Bajo'), ('Nivel 3', 'Medio'), ('Nivel 4', 'Alto'), ('Nivel 5', 'Máximo')], max_length=10, null=True),
        ),
    ]
