# Generated by Django 4.2.6 on 2024-06-19 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0018_calculos_horasexdiu_calculos_horasexfestivadiu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculos',
            name='antiguedad',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
