# Generated by Django 4.2.6 on 2024-06-19 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0019_calculos_antiguedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='antiguedad',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
