# Generated by Django 4.2.6 on 2024-06-19 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresarial', '0020_empleado_antiguedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculos',
            name='pension_empleador',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='calculos',
            name='salud_empeador',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
